version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    depends_on:
      - mysql

  web:
    image: nginx:1.17.3
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/app:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1